### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#225] opened 2020-04-30 13:06 UTC
At https://datanator.info/reaction/Potassium%20ferrocyanoferrate(II),O2--%3EUnknown,H2O/Escherichia%20coli click on 'Unknown’ fails
Accessing https://datanator.info/metabolite/2-Hydroxybenzyladenine/Escherichia%20coli generates server error.

**Comment by lzy7071** [comment] 2020-04-30 19:15
This is initially caused by a NoneType exception error. There is still an error now because there is no metabolite named `2-Hydroxybenzyladenine` in `metabolite_meta` because the meta collection was built from metabolites in [ecmdb](http://ecmdb.ca/unearth/q?utf8=%E2%9C%93&query=2-Hydroxybenzyladenine&searcher=organism_compounds&organism_id=1&button=) and [ymdb](http://www.ymdb.ca/unearth/q?utf8=%E2%9C%93&query=2-Hydroxybenzyladenine&searcher=compounds&button=).

**Comment by yosefdroth** [comment] 2020-05-13 12:29
solved in update_metab

**Comment by jonrkarr** [comment] 2020-05-14 17:08
The second example still generates a server error
http://localhost:3000/metabolite/2-Hydroxybenzyladenine/Escherichia%20coli

**Comment by lzy7071** [comment] 2020-05-14 17:13
> The second example still generates a server error
> http://localhost:3000/metabolite/2-Hydroxybenzyladenine/Escherichia%20coli

1. I think the URL should have been [datanator.info/metabolite/PHKMLSOXANWAKN-UHFFFAOYSA-N/Escherichia%20coli](https://datanator.info/metabolite/PHKMLSOXANWAKN-UHFFFAOYSA-N/Escherichia%20coli%20E1002)
2. https://github.com/KarrLab/datanator_frontend/issues/222#issuecomment-628757703

**Comment by jonrkarr** [comment] 2020-05-20 13:52
This still displays an error
http://localhost:3000/metabolite/PHKMLSOXANWAKN-UHFFFAOYSA-N/Escherichia%20coli%20E1002

**Comment by lzy7071** [comment] 2020-05-20 15:11
> This still displays an error
> http://localhost:3000/metabolite/PHKMLSOXANWAKN-UHFFFAOYSA-N/Escherichia%20coli%20E1002

That was my bad, the inchikey for 2-hydroxyhexadecanal is [BKBDVQVDRVGXKT-UHFFFAOYSA-N](http://www.ymdb.ca/compounds/YMDB00763). So the actual link should have been [https://datanator.info/metabolite/BKBDVQVDRVGXKT-UHFFFAOYSA-N/Escherichia%20coli%20E1002](https://datanator.info/metabolite/BKBDVQVDRVGXKT-UHFFFAOYSA-N/Escherichia%20coli%20E1002).

It is still giving an error, perhaps the reason being endpoint `/metabolites/concentration/?metabolite=` [https://api.datanator.info/metabolites/concentration/?metabolite=BKBDVQVDRVGXKT-UHFFFAOYSA-N&abstract=true&species=Escherichia%20coli%20E1002](https://api.datanator.info/metabolites/concentration/?metabolite=BKBDVQVDRVGXKT-UHFFFAOYSA-N&abstract=true&species=Escherichia%20coli%20E1002) is still being used. The endpoint is obsolete and it takes metabolite name rather than inchikey as the query parameter.

To retrieve [concentration information](https://github.com/KarrLab/datanator_rest_api/issues/71#issuecomment-631513030), one should use `/metabolites/concentrations/similar_compounds/` [http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=BKBDVQVDRVGXKT-UHFFFAOYSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=false
](http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=BKBDVQVDRVGXKT-UHFFFAOYSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=false
).

**Comment by jonrkarr** [comment] 2020-05-20 17:54
The `update_metab` branch is using the new endpoint. This isn't integrated into the master branch yet, and deployed.

**Comment by jonrkarr** [comment] 2020-05-20 19:49
I think this is now fixed.

**Closed by jonrkarr** 2020-05-20 19:49 UTC
Labels: bug
